controller_list:
  - name: fake_head_group_controller
    joints:
      - head_y
      - head_p
  - name: fake_torso_group_controller
    joints:
      - torso_y
  - name: fake_l_arm_group_controller
    joints:
      - l_arm_sh_p1
      - l_arm_sh_r
      - l_arm_sh_p2
      - l_arm_el_y
      - l_arm_wr_r
      - l_arm_wr_y
      - l_arm_wr_p
  - name: fake_r_arm_group_controller
    joints:
      - r_arm_sh_p1
      - r_arm_sh_r
      - r_arm_sh_p2
      - r_arm_el_y
      - r_arm_wr_r
      - r_arm_wr_y
      - r_arm_wr_p
  - name: fake_both_arm_group_controller
    joints:
      - torso_y
      - l_arm_sh_p1
      - l_arm_sh_r
      - l_arm_sh_p2
      - l_arm_el_y
      - l_arm_wr_r
      - l_arm_wr_y
      - l_arm_wr_p
      - r_arm_sh_p1
      - r_arm_sh_r
      - r_arm_sh_p2
      - r_arm_el_y
      - r_arm_wr_r
      - r_arm_wr_y
      - r_arm_wr_p
  - name: fake_r_leg_group_controller
    joints:
      - r_leg_hip_y
      - r_leg_hip_r
      - r_leg_hip_p
      - r_leg_kn_p
      - r_leg_an_p
      - r_leg_an_r
  - name: fake_l_leg_group_controller
    joints:
      - l_leg_hip_y
      - l_leg_hip_r
      - l_leg_hip_p
      - l_leg_kn_p
      - l_leg_an_p
      - l_leg_an_r
  - name: fake_lower_body_group_controller
    joints:
      - l_leg_hip_y
      - l_leg_hip_r
      - l_leg_hip_p
      - l_leg_kn_p
      - l_leg_an_p
      - l_leg_an_r
      - r_leg_hip_y
      - r_leg_hip_r
      - r_leg_hip_p
      - r_leg_kn_p
      - r_leg_an_p
      - r_leg_an_r
      - torso_y
  - name: fake_both_arms_with_torso_group_controller
    joints:
      - torso_y
      - l_arm_sh_p1
      - l_arm_sh_r
      - l_arm_sh_p2
      - l_arm_el_y
      - l_arm_wr_r
      - l_arm_wr_y
      - l_arm_wr_p
      - r_arm_sh_p1
      - r_arm_sh_r
      - r_arm_sh_p2
      - r_arm_el_y
      - r_arm_wr_r
      - r_arm_wr_y
      - r_arm_wr_p
  - name: fake_l_arm_with_torso_group_controller
    joints:
      - torso_y
      - l_arm_sh_p1
      - l_arm_sh_r
      - l_arm_sh_p2
      - l_arm_el_y
      - l_arm_wr_r
      - l_arm_wr_y
      - l_arm_wr_p
  - name: fake_r_arm_with_torso_group_controller
    joints:
      - torso_y
      - r_arm_sh_p1
      - r_arm_sh_r
      - r_arm_sh_p2
      - r_arm_el_y
      - r_arm_wr_r
      - r_arm_wr_y
      - r_arm_wr_p
  - name: fake_whole_body_group_controller
    joints:
      - l_leg_hip_y
      - l_leg_hip_r
      - l_leg_hip_p
      - l_leg_kn_p
      - l_leg_an_p
      - l_leg_an_r
      - r_leg_hip_y
      - r_leg_hip_r
      - r_leg_hip_p
      - r_leg_kn_p
      - r_leg_an_p
      - r_leg_an_r
      - torso_y
      - head_y
      - head_p
      - l_arm_sh_p1
      - l_arm_sh_r
      - l_arm_sh_p2
      - l_arm_el_y
      - l_arm_wr_r
      - l_arm_wr_y
      - l_arm_wr_p
      - r_arm_sh_p1
      - r_arm_sh_r
      - r_arm_sh_p2
      - r_arm_el_y
      - r_arm_wr_r
      - r_arm_wr_y
      - r_arm_wr_p
  - name: fake_all_appendages_group_controller
    joints:
      - l_leg_hip_y
      - l_leg_hip_r
      - l_leg_hip_p
      - l_leg_kn_p
      - l_leg_an_p
      - l_leg_an_r
      - r_leg_hip_y
      - r_leg_hip_r
      - r_leg_hip_p
      - r_leg_kn_p
      - r_leg_an_p
      - r_leg_an_r
      - l_arm_sh_p1
      - l_arm_sh_r
      - l_arm_sh_p2
      - l_arm_el_y
      - l_arm_wr_r
      - l_arm_wr_y
      - l_arm_wr_p
      - r_arm_sh_p1
      - r_arm_sh_r
      - r_arm_sh_p2
      - r_arm_el_y
      - r_arm_wr_r
      - r_arm_wr_y
      - r_arm_wr_p